### ISSUE TITLE
removing local .nuget dependency to Visualstudio BuiltIn.

### ISSUE THREAD

**Issue by rasyidf** [Dirkster99/Edi#1]
the **nuget** package manager in this repo is not using the build in NPM. that can cause some issue in the future.

**Comment by Dirkster99** [comment]
I guys we should change this then to use the build in NPM only. What are the correct steps to change this?
I would change it if I knew how....

**Comment by Dirkster99** [comment]
I tested the branch with the global changes - it works fine for me (VS 2017 Community) so lets commit it to the master branch...

1> Can you commit the test branch to the master branch or should I do it?
2> How did you make this change? Do you have a reference guide for this?
I am asking because I have other projects with the same issue so I'll change then as well ...

**Comment by rasyidf** [comment]
I just removing NPM Dependency on every project file (i.e EDI.csproj)

By searching every instance of this string in solution
`  <Import Project="$(SolutionDir)\.nuget\NuGet.targets" `
and removing it's block.

**Comment by rasyidf** [comment]
I have merged commit into master branch.

Thanks.. :) I'll close this issue then.
