### ISSUE TITLE
Inconsistency between Namespace Folder.

### ISSUE THREAD

**Issue by rasyidf** [Dirkster99/Edi#5]
the Edi Solution contains many project and namespace, grouped in folder.

> Edi
> Edi.Core
> EdiApp
> EdiDialogs
> EdiDocuments
> Settings
> SettingsView
> Setup Edi
> SimpleControls
> Themes
> Tools
> Util

It's look messy and inconsistent, may be we should look at this approach.

> Edi
> Edi.Core
> Edi.App
> Edi.Dialogs
> Edi.Documents
> Edi.Settings
> Edi.Settings.View
> Edi.Setup
> Edi.Controls
> Edi.Themes
> Edi.Tools
> Edi.Util

**Comment by Dirkster99** [comment]
This change is in principle OK for me - I can do it as soon as I get a chance - its a lot of mechanical work and I thing I can do it in about 1-2 weeks as I am going to be offline for a week or so.

Seeing the Settings project I am reminded of the underlying SettingsModel project:
http://settingsmodel.codeplex.com/

which I should also clone to github.

Do you know if it is possible to setup dependencies between github projects such that others can see these dependencies and that we ourselves are aware of it?

**Comment by rasyidf** [comment]
I don't really know the result but, i found this tips for github repo :

> Splitting components into separate repositories comes with some serious pain.
> In no particular order:
> 
>  -   Making a change to a component requires a release
>  -  Takes time and can fail for lots of stupid reasons
>  -  Feels stupid for small changes
>  -  It requires manually setting up new builds for each component
>  -  Hinders the discoverability of repositories
>  -  Refactoring when not all the source is available in a single repository
>  -  In some setups (like ours) updating APIs requires a milestone release of the
>  -  product, and then the plugin, and then the product again
> 
I think that, 
Dependencies can be uploaded to Nuget. then we can update the other repository to lastest version.

what do you think about this approach?

**Comment by Dirkster99** [comment]
Nuget for dependencies is a good idea, but I have never published to nuget before, so this will be another new topic for me :-)

As far as the changes go, I would only change the namespace definitions in each module - So we are not really splitting existing modules - and while the change is not small I am thinking it is feasable with some search/replace work required...

-> how about this
   - I will make the change in a branch and we can disucss it when we see the result, OK?

**Comment by rasyidf** [comment]
That's sound better,
For each improvement, we use independent branch so we can discuss it's benefits.

**Comment by Dirkster99** [comment]
Please review the [RefactoreEdi](https://github.com/Dirkster99/Edi/tree/RefactoreEdi) branch

The branch still contains the EdiApp project (for references) but the project builds with the
EdiApp project **unloaded** in VS.

I have refacored the EdiApp project into an Edi.Apps project stored physically in the Edi folder.
I opted for Edi.Apps because the namespace Edi.App would otherwise have caused a conflict with the **App** class in the **Edi** project :-(

I discovered a wrong namespace EdiApp in Edi.Core, but I don't want to change this right now - would rather enter a seperate issue and fix this later ...

I think this should work correctly for Edi.Apps now.

Can you verify this or do you see further todos?

If you see no problems, I suggest to commit this to the master and keep going with another branch/component for the next component until this is through, its complicated but not extremly unpredictive and risky so I think we can get through this hopefully soon ...and will not need more than a minor version number being increaded ...

**Comment by Dirkster99** [comment]
I've refactored Edi.Core and EdiDialogs in the [RefactoredEdi_1](https://github.com/Dirkster99/Edi/tree/RefactoredEdi_1) branch.

For testing you can load the solution and unload the old EdiDialogs project - which is still there for references only.

Please review and let me know if I've overseen a problem as above ... thanks Dirk
